package {{ root_package }}.data.exceptions.codes;

public enum UserExceptionCode {
    DEFAULT_ERROR(1),
    INVALID_ARGUMENT_USER_ID(2),
    INVALID_ARGUMENT_NAME(3),
    INVALID_ARGUMENT_EMAIL(5),
    INVALID_ARGUMENT_PHONE(6),
    INVALID_ARGUMENT_BIRTH_DATE(7),
    INVALID_ARGUMENT_SOCIAL_SECURITY_NUMBER(8),
    INVALID_ARGUMENT_ADDRESS_ADDRESS_LINE(9),
    INVALID_ARGUMENT_ADDRESS_COUNTRY(11),
    INVALID_ARGUMENT_ADDRESS_STATE(12),
    INVALID_ARGUMENT_ADDRESS_CITY(13),
    INVALID_ARGUMENT_ADDRESS_ZIP(14),
    ACTIVE_USER_WITH_THIS_EMAIL_EXISTS(15),
    PHONE_NOT_PRESENT_IN_WHITELIST(16),
    VERIFIED_USER_WITH_THIS_SSN_EXISTS(17),
    VERIFIED_USER_WITH_THIS_EMAIL_EXISTS(18),
    VERIFIED_USER_WITH_THIS_PHONE_NUMBER_EXISTS(19),
    USER_EXISTS(20),
    USER_ACCOUNT_CREATION_STATUS_PENDING(21),
    INVALID_PHONE_TYPE(23),
    PHONE_OTP_CODE_NOT_VERIFIED(24),
    EMAIL_OTP_CODE_NOT_VERIFIED(25),
    USER_RISK_DECISION_IS_REJECT(26);
    private final int value;

    UserExceptionCode(int value) {
        this.value = value;
    }

    public int value() {
        return value;
    }
}
